import {
  TrendingUp,
  TrendingDown,
  Shield,
  ShieldCheck,
  BarChart2,
  BarChart3,
  PieChart,
  LineChart,
  Calculator,
  DollarSign,
  CreditCard,
  Wallet,
  Banknote,
  Coins,
  Receipt,
  FileText,
  FileCheck,
  FilePen,
  Briefcase,
  Building2,
  Users,
  UserCheck,
  Lightbulb,
  Zap,
  Rocket,
  Target,
  CheckCircle2,
  Clock,
  Globe,
  Lock,
  Star,
  Award,
  HeartHandshake,
  Handshake,
  LifeBuoy,
  Phone,
  Mail,
  ArrowRight,
  ChevronRight,
  type LucideIcon,
} from "lucide-react";

export const iconRegistry: Record<string, LucideIcon> = {
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "shield": Shield,
  "shield-check": ShieldCheck,
  "bar-chart": BarChart2,
  "bar-chart-3": BarChart3,
  "pie-chart": PieChart,
  "line-chart": LineChart,
  "calculator": Calculator,
  "dollar-sign": DollarSign,
  "credit-card": CreditCard,
  "wallet": Wallet,
  "banknote": Banknote,
  "coins": Coins,
  "receipt": Receipt,
  "file-text": FileText,
  "file-check": FileCheck,
  "file-pen": FilePen,
  "briefcase": Briefcase,
  "building": Building2,
  "users": Users,
  "user-check": UserCheck,
  "lightbulb": Lightbulb,
  "zap": Zap,
  "rocket": Rocket,
  "target": Target,
  "check-circle": CheckCircle2,
  "clock": Clock,
  "globe": Globe,
  "lock": Lock,
  "star": Star,
  "award": Award,
  "heart-handshake": HeartHandshake,
  "handshake": Handshake,
  "life-buoy": LifeBuoy,
  "phone": Phone,
  "mail": Mail,
  "arrow-right": ArrowRight,
  "chevron-right": ChevronRight,
};

export type IconName = keyof typeof iconRegistry;
export const iconNames = Object.keys(iconRegistry) as IconName[];
